### ISSUE TITLE
Newly created projects do not run and break ICE

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#117]
Newly created projects using the project generator do not run and break ICE when it is launched. This is because the package name for the Launcher and Model builders is incorrect. For example, the code will put this in the class value of plugin.xml:

org.eclipse.ice.triquetrum.TriquetrumWorkflowItemLauncherBuilder

but that class is actually in 

org.eclipse.ice.triquetrum.launcher.TriquetrumWorkflowItemLauncherBuilder

which differs by the addition of "launcher." after "triquetrum."

Attempting to run a plugin generated with this results in catastrophic errors that prevent the ICE core from loading. For example, 

Caused by: org.osgi.framework.BundleException: Exception in org.eclipse.ice.core.internal.Core.start() of bundle org.eclipse.ice.core.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:792)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:941)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:318)
	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
	at org.eclipse.osgi.container.Module.start(Module.java:439)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:454)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	... 76 more
Caused by: org.eclipse.core.runtime.CoreException: Plug-in org.eclipse.ice.triquetrum was unable to load class org.eclipse.ice.triquetrum.TriquetrumWorkflowItemLauncherBuilder.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:176)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.ice.item.ItemBuilder.getItemBuilders(ItemBuilder.java:105)
	at org.eclipse.ice.persistence.xml.XMLPersistenceExtensionFactory.create(XMLPersistenceExtensionFactory.java:65)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:262)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.ice.item.persistence.IPersistenceProvider.getProvider(IPersistenceProvider.java:153)
	at org.eclipse.ice.core.internal.Core.start(Core.java:222)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
	... 83 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.ice.triquetrum.TriquetrumWorkflowItemLauncherBuilder cannot be found by org.eclipse.ice.triquetrum_1.0.0.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:439)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:573)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:174)
	... 96 more

**Comment by arbennett** [comment]
Fixed as of c2c034110710962a47b234915caa9ea043f03c79
