### ISSUE TITLE
Random test failures in next HIPP build

### ISSUE THREAD

**Issue by jarrah42** [eclipse/ice#152]
I'm seeing fairly random test failures during the build. The latest is:

Tests run: 5, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.136 sec <<< FAILURE! - in org.eclipse.ice.datastructures.entry.test.FileEntryTester
checkAllowedValues(org.eclipse.ice.datastructures.entry.test.FileEntryTester)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError: expected:<13> but was:<0>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:631)
    at org.eclipse.ice.datastructures.entry.test.FileEntryTester.checkAllowedValues(FileEntryTester.java:109)

checkEquality(org.eclipse.ice.datastructures.entry.test.FileEntryTester)  Time elapsed: 0 sec
checkXMLPersistence(org.eclipse.ice.datastructures.entry.test.FileEntryTester)  Time elapsed: 0.01 sec
checkSetValue(org.eclipse.ice.datastructures.entry.test.FileEntryTester)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: null
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at org.eclipse.ice.datastructures.entry.test.FileEntryTester.checkSetValue(FileEntryTester.java:157)

**Comment by amccaskey** [comment]
Are there files in your ~/ICETests/itemData directory?

**Comment by jarrah42** [comment]
This is on the HIPP instance and was working before...

**Comment by jayjaybillings** [comment]
I think this particular failure is definitely random and not necessarily addressable.

We have some reoccurring pseudo-random tests in the client and Item that fail because of thread timing issues when hardware is under heavy load. These are in Item and Client. If those are popping up regularly, we can try to rewrite them.

Jay

From my phone.
________________________________
