### ISSUE TITLE
NPE in ReflectivityMode.process

### ISSUE THREAD

**Issue by jarrah42** [eclipse/ice#155]
The Python sample scripts call the processItem method:

coreService.processItem(reflectModel.getId(), "Calculate Reflectivity", 1)

which results in:

Traceback (most recent call last):
  File "(none)", line 48, in <module>
	at org.eclipse.ice.reflectivity.ReflectivityModel.process(ReflectivityModel.java:210)
	at org.eclipse.ice.core.internal.itemmanager.ItemManager.processItem(ItemManager.java:981)
	at org.eclipse.ice.core.internal.Core.processItem(Core.java:506)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

java.lang.NullPointerException: java.lang.NullPointerException

Note that this is using EASE 0.3.0 if that matters.

**Comment by jarrah42** [comment]
Jay said he'd look at it...

**Comment by jayjaybillings** [comment]
I believe this was fixed, so I'm closing this. Please reopen if you encounter it again.
