### ISSUE TITLE
ICE Restful web service is broken

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#249]
I'm running the 20160630 build of next and the restful webservice isn't working. @SmithRWORNL confirmed that it isn't running on his version of ICE either, so I don't know how long it has been broken.

This needs to be fixed immediately because the users are RNET are wanting to build on it.

**Comment by amccaskey** [comment]
This is related to #225 and #156

**Comment by amccaskey** [comment]
Quickly checked the mac run configuration - we have Jersey 1.17 running with javax.ws.rs 2.0.1. This is most likely the issue. 

My solution would be to update our Jersey version to 2+

**Comment by jayjaybillings** [comment]
Seems reasonable to me.

The test for this is if we can open a browser and go to localhost:8080/items and get an XML stream back with the list of available Item types. There is a basic test class in org.eclipse.ice.core.jaxrs.test that I think we need to test out in the build. We can redo it if we need to to be more like the JAX-RS tests on TASQC, which do a full client-server test using the Jersey Client.

**Comment by jayjaybillings** [comment]
So... this is weird... I was getting a 404 on my machine, and then it stopped working and now localhost:8080/ice pops up with the appropriate username and password request...

**Comment by jayjaybillings** [comment]
So I was able to get it working, apparently just by restarting it a hundred million times...
![ice-webinterface](https://cloud.githubusercontent.com/assets/6378849/17440097/1e4a9476-5af9-11e6-8665-ce2cb43fe940.png)

**Comment by jayjaybillings** [comment]
Or maybe going to the correct web address? localhost:8080 gives me a 404, but localhost:8080/ice behaves appropriately. 

@amccaskey and @SmithRWORNL - Can you confirm that localhost:8080/ice works for you?

**Comment by SmithRWORNL** [comment]
@jayjaybillings Both addresses are giving me nothing. I'll try opening up a few more instances and reply if any of them successfully access one of the pages.

**Comment by jayjaybillings** [comment]
@SmithRWORNL What version does ICE say you are using in Help->About?

**Comment by SmithRWORNL** [comment]
@jayjaybillings 
Version: next
Build id: 20160802

**Comment by amccaskey** [comment]
I'm running from the Mac run configuration and getting the same exception as #225 #156 

java.lang.AbstractMethodError: javax.ws.rs.core.UriBuilder.uri(Ljava/lang/String;)Ljavax/ws/rs/core/UriBuilder;
	at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:119) ~[na:na]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:649) ~[na:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet_3.1.0.v201410161800.jar:3.1.0]
	at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl$LegacyServlet.service(HttpServiceRuntimeImpl.java:1221) ~[na:na]
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[na:na]
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62) ~[na:na]
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:132) ~[na:na]
	at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.service(ProxyServlet.java:100) ~[na:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet_3.1.0.v201410161800.jar:3.1.0]
	at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:310) ~[org.eclipse.equinox.http.jetty_3.3.0.v20160324-1850.jar:na]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) ~[org.eclipse.jetty.servlet_9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583) [org.eclipse.jetty.servlet_9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224) [org.eclipse.jetty.server_9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174) [org.eclipse.jetty.server_9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [org.eclipse.jetty.servlet_9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [org.eclipse.jetty.server_9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106) [org.eclipse.jetty.server_9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [org.eclipse.jetty.server_9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [org.eclipse.jetty.server_9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.Server.handle(Server.java:524) [org.eclipse.jetty.server_9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319) [org.eclipse.jetty.server_9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253) [org.eclipse.jetty.server_9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [org.eclipse.jetty.io_9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [org.eclipse.jetty.io_9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [org.eclipse.jetty.io_9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [org.eclipse.jetty.util_9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [org.eclipse.jetty.util_9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [org.eclipse.jetty.util_9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [org.eclipse.jetty.util_9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [org.eclipse.jetty.util_9.3.9.v20160517.jar:9.3.9.v20160517]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]

**Comment by amccaskey** [comment]
As per #156 this gets thrown bc of the different versions of javax.ws.rs (1.0.x worked, 2+ does not)

**Comment by amccaskey** [comment]
I get the same exception downloading and running the 08-02-2016 build on Mac.

**Comment by jayjaybillings** [comment]
So I think as per #156 we need to switch back to javax.ws.rs 1.x, right?

**Comment by amccaskey** [comment]
@jarrah42 Did you remove it bc the Neon build wouldn't work with it?

**Comment by jarrah42** [comment]
Yes, 1.x has been removed from Orbit. We need to update to work with 2.0.1

**Comment by jayjaybillings** [comment]
@amccaskey So have the Docker shaded plugins been updated to work with 2.0.1? That's why we dropped back to 1.x.

**Comment by jayjaybillings** [comment]
@amccaskey told me that he didn't have any luck fixing this, so I'll take a look tonight or over the weekend.
