### ISSUE TITLE
ICE Next blank Workspace Error notifying preference change listener

### ISSUE THREAD

**Issue by amccaskey** [eclipse/ice#310]
Currently for our unstable build, starting a new instance of ICE with a new workspace displays error at startup (see picture). It says 'Error notifying preference change listener. NullPointerException' Here's the log: 

```code
java.lang.NullPointerException
        at org.eclipse.mylyn.internal.tasks.ui.TasksUiPlugin$2.propertyChange(TasksUiPlugin.java:296)
        at org.eclipse.ui.preferences.ScopedPreferenceStore$3.run(ScopedPreferenceStore.java:350)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.ui.preferences.ScopedPreferenceStore.firePropertyChangeEvent(ScopedPreferenceStore.java:346)
        at org.eclipse.ui.preferences.ScopedPreferenceStore.setValue(ScopedPreferenceStore.java:658)
        at org.eclipse.mylyn.internal.tasks.ui.TasksUiPlugin$TasksUiInitializationJob.hideNonMatchingSubtasks(TasksUiPlugin.java:418)
        at org.eclipse.mylyn.internal.tasks.ui.TasksUiPlugin$TasksUiInitializationJob.runInUIThread(TasksUiPlugin.java:406)
        at org.eclipse.ui.progress.UIJob$1.run(UIJob.java:97)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4033)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1133)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:698)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
```

This is high priority - issue VIBE currently has is fixed in next. With this fixed we can ship off ICE to them for their VM. 

![screen shot 2016-12-08 at 2 03 33 pm](https://cloud.githubusercontent.com/assets/827531/21024349/2705016c-bd52-11e6-899a-75ee47a48f2a.png)

**Comment by amccaskey** [comment]
Possibly related to - https://bugs.eclipse.org/bugs/show_bug.cgi?id=507006

**Comment by amccaskey** [comment]
Oops, duplicate of #304

**Comment by jayjaybillings** [comment]
The only way that I know of to fix this is to drop Mylyn or figure out if there are Mylyn bundles that are missing. @jarrah42 what do you think?

**Comment by amccaskey** [comment]
Removing *.mylyn.* from the ice_sdk.product file fixes this issue.

**Comment by jarrah42** [comment]
Oxygen M4 is next week. Presumably the change should be in that build, so is it worth waiting to see if it is fixed?

**Comment by amccaskey** [comment]
I say we try to put the features back in then, only thing now is that the VIBE team needs a working binary for the release of there VM.

**Comment by jarrah42** [comment]
Fine by me.

**Comment by jayjaybillings** [comment]
Let's leave this open until after the M4.

**Comment by jayjaybillings** [comment]
Sorry for the slow response on this going into next. Thanks!
