### ISSUE TITLE
ICE 2.2.0 Unstable fails to start on CentOS 6

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#357]
The 2.2.0 Unstable build fails to start on CentOS 6 with the following error:
```java
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons:
        /home/jay/ICE-2.2.0/configuration/org.eclipse.osgi/735/0/.cp/libswt-pi-gtk-4735.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/jay/ICE-2.2.0/configuration/org.eclipse.osgi/735/0/.cp/libswt-pi-gtk-4735.so)
        no swt-pi-gtk in java.library.path
        /home/jay/.swt/lib/linux/x86_64/libswt-pi-gtk-4735.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/jay/.swt/lib/linux/x86_64/libswt-pi-gtk-4735.so)
        Can't load library: /home/jay/.swt/lib/linux/x86_64/libswt-pi-gtk.so

        at org.eclipse.swt.internal.Library.loadLibrary(Library.java:327)
        at org.eclipse.swt.internal.Library.loadLibrary(Library.java:236)
        at org.eclipse.swt.internal.gtk.OS.<clinit>(OS.java:28)
        at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:118)
        at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:80)
        at org.eclipse.swt.widgets.Display.<clinit>(Display.java:140)
        at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:769)
        at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:160)
        at org.eclipse.ui.internal.ide.application.IDEApplication.createDisplay(IDEApplication.java:168)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:111)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```
The system name is kernel is the 2.6 series and it is running Java 1.8.0_121. I think this is the default OpenJDK install.

I don't believe that we can fix or necessarily should fix this. Can someone just download the unstable nightly build and make sure it works for them? As long as the night executable works on other machines, I'll be satisfied to mark this as wont-fix given the machine I'm on.

**Comment by SmithRWORNL** [comment]
@jayjaybillings I was able to open the latest unstable nightly on a CentOS machine.

**Comment by jayjaybillings** [comment]
Cool. Closing as wont-fix.

**Comment by jayjaybillings** [comment]
And invalid.
