### ISSUE TITLE
ICE 2.2.1 RC3 is missing the Marketplace

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#371]
Not sure how it vanished, but it is gone on Windows, Mac and Linux. Thanks to @SmithRWORNL and Francis Cho for confirming.

**Comment by jarrah42** [comment]
You need to add the org.eclipse.epp.mpc feature. I think this got separated out at some point.

**Comment by jayjaybillings** [comment]
You're right. I'm looking at it now. This is probably my fault because of various product refactoring work I've been doing.

**Comment by jayjaybillings** [comment]
Actually, no, both rcp and sdk projects have these features. The plot thickens...
![screenshot from 2017-05-11 14-09-56](https://cloud.githubusercontent.com/assets/6378849/25964633/8e17178a-3653-11e7-8e67-5d58a65516ee.png)

**Comment by jayjaybillings** [comment]
My local build of 2.2.1RC3 has the Marketplace in it. I'm going to direct Hudson to rebuild its version.

**Comment by jarrah42** [comment]
The EPP packages list it as a dependency in the main feature.xml. You might want to give that a go.

**Comment by jayjaybillings** [comment]
Did that. No beans. The bundle is available, but not showing up in the menu. Any other suggestions? I'll dig around the forums if not.

**Comment by jayjaybillings** [comment]
I was looking at [this forum entry](https://www.eclipse.org/forums/index.php/t/1085206/) and got the idea to look at the log.
```java
!ENTRY org.eclipse.epp.mpc.core 4 0 2017-05-11 20:28:46.667
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.epp.mpc.core [328]
  Unresolved requirement: Require-Bundle: org.eclipse.userstorage.oauth; bundle-version="[1.0.0,1.2.0)"; resolution:="optional"
  Unresolved requirement: Require-Bundle: org.eclipse.userstorage; bundle-version="[1.0.1,1.2.0)"
    -> Bundle-SymbolicName: org.eclipse.userstorage; bundle-version="1.0.1.v20170201-1648"; singleton:="true"
       org.eclipse.userstorage [798]
         No resolution report for the bundle.  Bundle was not resolved because of a uses contraint violation.
  org.osgi.service.resolver.ResolutionException: Uses constraint violation. Unable to resolve resource org.eclipse.userstorage [osgi.identity; type="osgi.bundle"; version:Version="1.0.1.v20170201-1648"; osgi.identity="org.eclipse.userstorage"; singleton:="true"] because it is exposed to package 'org.apache.http' from resources org.apache.httpcomponents.httpcore [osgi.identity; type="osgi.bundle"; version:Version="4.3.3.v201411290715"; osgi.identity="org.apache.httpcomponents.httpcore"] and org.apache.httpcomponents.httpcore [osgi.identity; type="osgi.bundle"; version:Version="4.4.6.v20170210-0925"; osgi.identity="org.apache.httpcomponents.httpcore"] via two dependency chains.

Chain 1:
  org.eclipse.userstorage [osgi.identity; type="osgi.bundle"; version:Version="1.0.1.v20170201-1648"; osgi.identity="org.eclipse.userstorage"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.apache.httpcomponents.httpcore)(&(bundle-version>=4.0.0)(!(bundle-version>=4.4.0))))
     |
    provide: osgi.wiring.bundle: org.apache.httpcomponents.httpcore
  org.apache.httpcomponents.httpcore [osgi.identity; type="osgi.bundle"; version:Version="4.3.3.v201411290715"; osgi.identity="org.apache.httpcomponents.httpcore"]

Chain 2:
  org.eclipse.userstorage [osgi.identity; type="osgi.bundle"; version:Version="1.0.1.v20170201-1648"; osgi.identity="org.eclipse.userstorage"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.apache.httpcomponents.httpclient)(&(bundle-version>=4.0.0)(!(bundle-version>=4.4.0))))
     |
    provide: osgi.wiring.bundle; bundle-version:Version="4.3.6.v201511171540"; osgi.wiring.bundle="org.apache.httpcomponents.httpclient"
  org.apache.httpcomponents.httpclient [osgi.identity; type="osgi.bundle"; version:Version="4.3.6.v201511171540"; osgi.identity="org.apache.httpcomponents.httpclient"]
    import: (&(osgi.wiring.package=org.apache.http.protocol)(version>=4.3.3))
     |
    export: osgi.wiring.package: org.apache.http.protocol; uses:=org.apache.http
    export: osgi.wiring.package=org.apache.http
  org.apache.httpcomponents.httpcore [osgi.identity; type="osgi.bundle"; version:Version="4.4.6.v20170210-0925"; osgi.identity="org.apache.httpcomponents.httpcore"]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1628)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1607)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1579)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1522)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```

**Comment by jarrah42** [comment]
Good catch.

**Comment by jayjaybillings** [comment]
@jarrah42 Is there any chance you can take a look at this today? I just pushed an updated feature on the 2.2.1 branch, but it still isn't working. 

Normally these double wiring problems mean that we are getting the bundle from two sources that require two different versions. I'm not sure where we are pulling them in.

**Comment by jayjaybillings** [comment]
Based on what I can glean from discussions on the forums and in Bugzilla tickets, it looks like this is a bug that won't be fixed until Oxygen is much closer to being fully released. #poop

I also downloaded the M6 "Eclipse for Testers" build and tried it to confirm this. I behaves exactly as ICE does: it has the MPC bundle, but it won't start because of the user storage bug.

**Comment by jayjaybillings** [comment]
Let's vote on it: Do we ship 2.2.1 without the Marketplace?

My vote: Yes. The workaround is to just use the regular installer with updates sites. While not perfect, it will work just fine until the Oxygen fix. I don't think the Marketplace is an absolutely critical feature, just a convenient one.

**Comment by jarrah42** [comment]
+1

**Comment by SmithRWORNL** [comment]
+1

We shouldn't hold up the release just for the marketplace.

**Comment by amccaskey** [comment]
+1

**Comment by jayjaybillings** [comment]
Alright. I'll try to get it out today. Thanks!

**Comment by jayjaybillings** [comment]
This issue is finished, but I'm still trying to get the final release out.

**Comment by jayjaybillings** [comment]
The actual 2.2.1 release has the marketplace in it, so I suppose they fixed the bug and we picked up the fix.
