### ISSUE TITLE
File copy bug in mccaskey/joblauncherRefactor

### ISSUE THREAD

**Issue by amccaskey** [eclipse/ice#66]
Steps to replicate: 

1. Create Existing Moose Workflow Item
2. Launch (succeeds) 
3. Invalidate the Tree
4. Launch to get appropriate tree validation error
5. Fix tree and relaunch (expected successful execution)

The JobLaunchAction fails to copy files to the local iceLaunch_* directory. Specifically, we get 

17:33:52.325 [Thread-175] INFO  o.e.ice.item.action.JobLaunchAction - JobLaunchAction copying launchJob_20151214053326.sh to local job launch folder: /Users/aqw/iceworkspace/moose_test_project/jobs/iceLaunch_20151214053352.
17:33:52.329 [Thread-175] ERROR o.e.ice.item.action.JobLaunchAction - JobLaunchAction Error - Could not copy files from the project space to the job folder.
org.eclipse.core.internal.resources.ResourceException: Resource '/moose_test_project/launchJob_20151214053326.sh' does not exist.
	at org.eclipse.core.internal.resources.Resource.checkExists(Resource.java:334) ~[na:na]
	at org.eclipse.core.internal.resources.Resource.checkAccessible(Resource.java:208) ~[na:na]
	at org.eclipse.core.internal.resources.File.getContents(File.java:267) ~[na:na]
	at org.eclipse.core.internal.resources.File.getContents(File.java:260) ~[na:na]
	at org.eclipse.ice.item.action.JobLaunchAction.run(JobLaunchAction.java:1464) ~[na:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]

I've only seen this in the new joblauncherRefactor branch, so I probably introduced it somehow. Starting this tracker mainly as a reminder to fix this.

**Comment by amccaskey** [comment]
Turns out this was happening because the map of files to be uploaded was persisting between JobLaunchAction executions, so the previous launch script was being included in the current file upload, and it didn't exist. Upcoming commit will fix this.
